name: Basic CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CUSTOM_ENV_VAR: "Valeur perso"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run application check script
        run: bash ./app/check_app.sh

      - name: Display index.html content
        run: cat ./app/index.html

      - name: Afficher secrets et variables d'environnement
        run: |
          echo "ğŸ” FAKE_API_TOKEN = ${{ secrets.FAKE_API_TOKEN }}"
          echo "ğŸ›  ENV_TYPE = ${{ secrets.ENV_TYPE }}"
          echo "ğŸŒ RUNNER_OS = $RUNNER_OS"
          echo "ğŸ§ª CUSTOM_ENV_VAR = $CUSTOM_ENV_VAR"
